### ISSUE TITLE
Cannot play any media

### ISSUE THREAD

**Issue by celestinecypoon** [plexinc-plugins/SoundCloud.bundle#22]
**Device: iPad Mini 4** 
**Device OS: 9.3.1** 
**App Build: 4.0.15 (latest internal), buddybuild #5577** 
**PMS Build: --** 

**Steps to Reproduce:**

1. on the iPad, open menu --> channels --> SoundCloud
2. select any SoundCloud file to play

**Current Behaviour:**
Error returned: `Something went wrong playing your media. Please try again.`

Log:
[PlexDebugInfo (1).zip](https://github.com/plexinc-plugins/SoundCloud.bundle/files/239556/PlexDebugInfo.1.zip)

**Comment by sander1** [comment]
Can you please post the `com.plexapp.plugins.soundcloud.log` and `com.plexapp.system.log` log files?

**Comment by celestinecypoon** [comment]
Tried this on pms: 9.16 and 9.17, both working fine
I believe this is a PMS specific issue where it is only happening on that particular server. Will close this as it is not soundcloud related.
